background_opacity = 1

[colors]
draw_bold_text_with_bright_colors = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[colors.bright]
black = "0x434758"
blue = "0x9cc4ff"
cyan = "0xa3f7ff"
green = "0xddffa7"
magenta = "0xe1acff"
red = "0xff8b92"
white = "0xffffff"
yellow = "0xffe585"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "0x282a36"
blue = "0x82aaff"
cyan = "0x89ddff"
green = "0xc3e88d"
magenta = "0xc792ea"
red = "0xf07178"
white = "0xd0d0d0"
yellow = "0xffcb6b"

[colors.primary]
background = "0x282a36"
bright_foreground = "#eaeaea"
dim_foreground = "#828482"
foreground = "0xbbc5ff"

[colors.selection]
background = "0xbbc5ff"
text = "0x282a36"

[colors.vi_mode_cursor]
cursor = "#ffffff"
text = "#000000"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "OFF"
persistent_logging = false
print_events = false
ref_test = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "SourceCodePro"
style = "Bold"

[font.italic]
family = "Nerd Font Mono"
style = "Italic"

[font.normal]
family = "SourceCodePro"
style = "Regular"

[font.offset]
x = 0
y = 0

[glyph_offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[mouse.double_click]
threshold = 300

[mouse.triple_click]
threshold = 300

[scrolling]
history = 0
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''

[window]
decorations = "full"
dynamic_padding = false
tabspaces = 2
title = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 4
y = 6
