"""""""""""""""""""""""""
" nolimitcarter's vimrc "
"""""""""""""""""""""""""

" WIP detection of major operating systems 
"[ -z "$OS" ] && export OS=`uname`
"case "$OS" in
"  Linux)          export PLATFORM=linux ;;
"  *indows*)       export PLATFORM=windows ;;
"  FreeBSD|Darwin) export PLATFORM=mac ;;
"  *)              export PLATFORM=unknown ;;
"esac

" syntaxing / cursor line
syntax enable
set encoding=utf-8
set cul 
hi CursorLine term=none cterm=none ctermbg=none
filetype on
filetype plugin on
let g:ycm_global_ycm_extra_conf = "~/.vim/.ycm_extra_conf.py"
noremap B ^ 
noremap E $
noremap gv `[V`]
set cmdheight=1

" formatting bye tabs 
set tabstop=2
set softtabstop=2
set shiftwidth=2
set smarttab
set nu
set expandtab
set nobackup
set noerrorbells

" colors and shell styles
" default colors are nice tho @ gruvbox
"colorscheme gruvbox
set background=dark
set scrollfocus
set showmode
set showcmd
set ttyfast
set shell=bash

" hightlights search (use :noh to clear the highlights, n can turn back on)
set hlsearch
set incsearch
set showmatch " new

" auto y for Y/N installs
"set shortmess=ao0tI 

" memory management
" stops complaints about switching buffer with changes
set hidden
set history=100

" display
set smartindent
set linebreak
set icon
set ruler
set nocompatible
set nowrap 
set showbreak=▹ 

" autocomplete in insert mode on ctrl+N 
set complete
set completeopt
set wildmenu

" universal copy and paste, prevents yanks and deletes
set viminfo='20,<1000,s1000

" plugins
call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'vim-pandoc/vim-pandoc'
Plug 'airblade/vim-gitgutter'
Plug 'faith/vim-go'
Plug 'ycm-core/YouCompleteMe'
call plug#end()

" airline plugin
" ---Airline---
set t_Co=256
let g:Powerline_symbols = "fancy"
let g:airline_powerline_fonts = 1
let g:airline_theme = 'minimalist' " listing good themes= zenburn, wombat, seagull, peaksea, minimalist, lucius
let g:airline_skip_empty_sections = 1
let g:airline#extensions#tabline#enabled = 0 "0 for top gone
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline#extensions#tabline#formatter = 'unique_tail'


" remember where you were last time editing 
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" formatting 
set formatoptions-=a " disables autoformatting 
map <f4> :set list!<CR>
imap ii <C-[>  

" WIP GO plugin options
"  let g:go_fmt_command = 'goimports'
"  let g:go_fmt_autosave = 1
"else
"  autocmd vimleavepre *.go !gofmt -w %
"endif 


" spelling
if v:version >= 700
        " Enable spell check for text files
        autocmd BufNewFile,BufRead *.txt,.md setlocal spell spelllang=en
endif

au syntax * hi SpellBad ctermfg=White ctermbg=Red cterm=none

