"""""""""""""""""""""""""
" nolimitcarter's vimrc "
"""""""""""""""""""""""""

" WIP detection of major operating systems 
"[ -z "$OS" ] && export OS=`uname`
"case "$OS" in
"  Linux)          export PLATFORM=linux ;;
"  *indows*)       export PLATFORM=windows ;;
"  FreeBSD|Darwin) export PLATFORM=mac ;;
"  *)              export PLATFORM=unknown ;;
"esac

" syntaxing / cursor line
syntax enable
set cul 
hi CursorLine term=none cterm=none ctermbg=none
filetype on
filetype plugin on
noremap B ^ 
noremap E $
noremap gv `[V`]

" formatting 
set tabstop=2
set softtabstop=2
set shiftwidth=2
set smarttab
set nu
set expandtab
set nobackup
"colorscheme gruvbox
set background=dark
set scrollfocus
set showmode
set showcmd
set ttyfast
set shell=bash

" hightlights search (use :noh to clear the highlights, n can turn back on)
set hlsearch
set incsearch
set showmatch " new

" auto y for Y/N installs
"set shortmess=ao0tI 

" universal copy and paste, prevents truncated yanks and deletes
set viminfo='20,<1000,s1000

" memory management
" stops complaints about switching buffer with changes
set hidden
set history=100

" display / smart formatting
set wildmenu
set smartindent
set linebreak
set icon
set ruler
set nocompatible
set nowrap " new
set showbreak=▹ " new 

" remember where you were last time editing 
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" formatting WIP
set formatoptions-=a " disables autoformatting 
map <f4> :set list!<CR>
imap ii <C-[>  

" install vim-plug if not already installed
" (Yes I know about Vim 8 Plugins. They suck.)
if empty(glob('~/.vim/autoload/plug.vim'))
   silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
   autocmd VimEnter * PlugInstall
endif

" installs plugins WIP
"if filereadable(expand("~/.vim/autoload/plug.vim"))
"  call plug#begin('~/.vimplugins')
"  Plug 'vim-pandoc/vim-pandoc'
"  Plug 'https://gitlab.com/rwxrob/vim-pandoc-syntax-simple'
"  Plug 'cespare/vim-toml'
"  Plug 'faith/vim=go'
"  Plug 'airblade/vim-gitgutter'
"  Plug 'PProvost/vim-ps1'
"  call plug#end()
"  let g:go_fmt_fail_silently = 0
"  let g:go_fmt_command = 'goimports'
"  let g:go_fmt_autosave = 1
"else
"  autocmd vimleavepre *.go !gofmt -w %
"endif 


" spelling
if v:version >= 700
        " Enable spell check for text files
        autocmd BufNewFile,BufRead *.txt,.md setlocal spell spelllang=en
endif

au syntax * hi SpellBad ctermfg=White ctermbg=Red cterm=none

