#!/bin/sh
# helpful script taken from https://github.com/rwxrob/dotfiles/blob/main/scripts/cheat

cheat() {
  where="$1"
  if [ $# -ge 1 ]; then
    shift
  fi
  IFS=+ curl -sS "http://cht.sh/$where/ $*"
}

cheat "$@"

