#!/bin/sh

xrandr --output DP-1 --primary --mode 2560x1080 --pos 1080x1080 --rotate normal --output eDP-1 --off --output DP-3 --mode 1920x1080 --pos 1080x1080 --right-of DP-1 --rotate normal 

#xrandr --output eDP-1 --primary --mode 1920x1080 --pos 1080x1080 --rotate normal 
