#!/bin/bash

xrandr --output DisplayPort-2 --above HDMI-A-0
xrandr --output DisplayPort-1 --left-of HDMI-A-0
xrandr --output DisplayPort-1 --left-of DisplayPort-2
xrandr --output DisplayPort-1 --roate right
