#!/bin/bash

my_pc_monitors=$(xrandr --query | grep 'XWAYLAND0,XWAYLAND1,XWAYLAND2')
if [[ $my_pc_monitors = *connected ]]; then
  xrandr --output XWAYLAND1 --primary --mode 1920x1080 --rotate normal --output XWAYLAND0 --mode 1080x1920 --rotate 90% --left-of XWAYLAND1 --output XWAYLAND2 --mode 1920x1080 --rotate normal --top-of XWAYLAND1
fi
