export PATH=\
$HOME/bin:\
$HOME/go/bin:\
$HOME/.cargo/bin:\
/usr/local/go/bin:\
/usr/local/bin:\
/usr/local/sbin:\
/usr/sbin:\
/usr/bin:\
/snap/bin:\
/sbin:\
/bin:\

if [[ ${EUID} == 0 ]] ; then
	  PS1='\[\033[01;31m\][\h\[\033[01;36m\] \W\[\033[01;31m\]]\$\[\033[00m\] '
  else
	  PS1='\033[35m\][\W]\[\033[00;00m\] \[\033[00;34m\]boostmod3\[\033[1;33m\]-> \[\033[0m\]'
fi

